#!/usr/bin/env bash
# gpu-setup.sh — Detect external display on NVIDIA and generate gpu.conf
#
# Writes ~/.config/hypr/gpu.conf with the right env vars:
#   - External monitor on NVIDIA DP → both GPUs, nvidia VAAPI
#   - No external monitor → Intel only, iHD VAAPI, dGPU can suspend
#
# Usage:
#   gpu-setup.sh          # generate gpu.conf
#   gpu-setup.sh status   # print current mode without writing

set -euo pipefail

GPU_CONF="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/gpu.conf"

# Stable by-path references (immune to card number reordering across reboots)
INTEL_CARD="/dev/dri/by-path/pci-0000:00:02.0-card"
NVIDIA_CARD="/dev/dri/by-path/pci-0000:01:00.0-card"

detect_nvidia_display() {
    # Check if any connector on the NVIDIA GPU reports "connected"
    local nvidia_pci="0000:01:00.0"
    for connector in /sys/class/drm/card*-*/status; do
        # Match connectors belonging to the NVIDIA card
        local card_dir
        card_dir="$(dirname "$(dirname "$connector")")"
        local device_link
        device_link="$(readlink -f "$card_dir/device" 2>/dev/null || true)"
        if [[ "$device_link" == *"$nvidia_pci"* ]]; then
            if [[ "$(cat "$connector" 2>/dev/null)" == "connected" ]]; then
                return 0
            fi
        fi
    done
    return 1
}

write_hybrid_conf() {
    cat > "$GPU_CONF" <<'EOF'
# gpu.conf — AUTO-GENERATED by gpu-setup.sh
# Mode: HYBRID (Intel + NVIDIA, external display detected)

env = AQ_DRM_DEVICES,/dev/dri/by-path/pci-0000:00:02.0-card:/dev/dri/by-path/pci-0000:01:00.0-card

env = LIBVA_DRIVER_NAME,nvidia
env = NVD_BACKEND,direct
EOF
    echo "hybrid"
}

write_intel_conf() {
    cat > "$GPU_CONF" <<'EOF'
# gpu.conf — AUTO-GENERATED by gpu-setup.sh
# Mode: INTEL-ONLY (no external display, dGPU can suspend)

env = AQ_DRM_DEVICES,/dev/dri/by-path/pci-0000:00:02.0-card

env = LIBVA_DRIVER_NAME,iHD
EOF
    echo "intel"
}

main() {
    if detect_nvidia_display; then
        local mode
        mode="$(write_hybrid_conf)"
    else
        local mode
        mode="$(write_intel_conf)"
    fi

    if [[ "${1:-}" == "status" ]]; then
        echo "GPU mode: $mode"
        echo "Config: $GPU_CONF"
        cat "$GPU_CONF"
    fi
}

main "$@"
