# Application bindings
$terminal = ghostty
$browser = vivaldi-stable --new-window

# --- Workspace managment ---
unbind = SUPER, 1
unbind = SUPER, 2
unbind = SUPER, 3
unbind = SUPER, 4
unbind = SUPER, 5
unbind = SUPER, 6
unbind = SUPER, 7
unbind = SUPER, 8
unbind = SUPER, 9
unbind = SUPER, 0

unbind = SUPER SHIFT, 1
unbind = SUPER SHIFT, 2
unbind = SUPER SHIFT, 3
unbind = SUPER SHIFT, 4
unbind = SUPER SHIFT, 5
unbind = SUPER SHIFT, 6
unbind = SUPER SHIFT, 7
unbind = SUPER SHIFT, 8
unbind = SUPER SHIFT, 9
unbind = SUPER SHIFT, 0

# Bind Alt + [Number] to switch to workspace (1-10)
bind = ALT, 1, workspace, 1
bind = ALT, 2, workspace, 2
bind = ALT, 3, workspace, 3
bind = ALT, 4, workspace, 4
bind = ALT, 5, workspace, 5
bind = ALT, 6, workspace, 6
bind = ALT, 7, workspace, 7
bind = ALT, 8, workspace, 8
bind = ALT, 9, workspace, 9
bind = ALT, 0, workspace, 10

# Bind Alt + Shift + [Number] to move active window to workspace (1-10)
bind = ALT SHIFT, 1, movetoworkspace, 1
bind = ALT SHIFT, 2, movetoworkspace, 2
bind = ALT SHIFT, 3, movetoworkspace, 3
bind = ALT SHIFT, 4, movetoworkspace, 4
bind = ALT SHIFT, 5, movetoworkspace, 5
bind = ALT SHIFT, 6, movetoworkspace, 6
bind = ALT SHIFT, 7, movetoworkspace, 7
bind = ALT SHIFT, 8, movetoworkspace, 8
bind = ALT SHIFT, 9, movetoworkspace, 9
bind = ALT SHIFT, 0, movetoworkspace, 10

# --- Resizing Windows --
binde = ALT, U, resizeactive, -20 0
binde = ALT, I, resizeactive, 0 20
binde = ALT, O, resizeactive, 0 -20
binde = ALT, P, resizeactive, 20 0


# --- Window managment ---
unbind = SUPER, F
unbind = SUPER, T
unbind = SUPER ALT, F

bind = CONTROL, RETURN, exec, 
bind = CONTROL, ENTER, exec,

# Fullscreen window
bind = ALT, F, fullscreen, 1
bind = ALT SHIFT, F, fullscreen, 0

# Tiling windows
bind = ALT, T, togglefloating
bind = SUPER, T, togglegroup
bind = ALT SHIFT, T, settiled

# Center window to the middle of the screen, when tiled
bind = ALT, C, centerwindow

# --- Window Cycling ---
# Cycle forward and bring the active window to the top of the Z-order
bind = ALT, Tab, cyclenext,
bind = ALT, Tab, bringactivetotop,

# Optional: Cycle backward using Shift
bind = ALT SHIFT, Tab, cyclenext, prev
bind = ALT SHIFT, Tab, bringactivetotop,


# --- Window Navigation (Vim-style) ---
# Move focus with ALT + HJKL
unbind = SUPER, h
unbind = SUPER, l
unbind = SUPER, k
unbind = SUPER, j


# Close window
unbind = SUPER, W
bind = ALT SHIFT, q, killactive

# Lock screen
bind = SUPER, l, exec, qs -c noctalia-shell ipc call lockScreen lock

# --- Window Movement (Vim-style) ---
# Move tiled windows in the given direction
bind = ALT SHIFT, h, movewindow, l
bind = ALT SHIFT, l, movewindow, r
bind = ALT SHIFT, k, movewindow, u
bind = ALT SHIFT, j, movewindow, d

bind = ALT, h, movefocus, l
bind = ALT, l, movefocus, r
bind = ALT, k, movefocus, u
bind = ALT, j, movefocus, d

# --- Aplication shortcuts ---
bind = SUPER, E, exec, nautilus
bindd = SUPER SHIFT, T, Activity, exec, $terminal -e btop
bind = SUPER SHIFT, N, exec, qs -c noctalia-shell ipc call controlCenter toggle
bindd = ALT SHIFT, O, Obsidian ,exec, obsidian
bindd = ALT SHIFT, B, Browser, exec, $browser
bindd = ALT, RETURN, Terminal, exec, $terminal
bindd = ALT SHIFT, D, Docker, exec, $terminal -e lazydocker

bind = SUPER, W, exec, qs -c noctalia-shell ipc call wallpaper toggle
# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
bindd = ALT, SPACE, Launch apps, exec, qs -c noctalia-shell ipc call launcher toggle


bind = SUPER SHIFT, S, exec, grim -g "$(slurp)" - | wl-copy
