# Disables hardware cursors
# Fixes the "glitchy" mouse, trails, and artifacts caused by
# mixed-scaling on NVIDIA. This forces Hyprland to draw the
# cursor in software, which solves the rendering bug.
cursor {
    no_hardware_cursors = true
}



# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf


xwayland {
  # Tells XWayland apps to handle their own scaling
  # This can make them sharp, but some may be tiny.
  force_zero_scaling = true
}

source = /home/mael/.config/hypr/noctalia/noctalia-colors.conf

