-- Ported from workspaces.conf (generated by nwg-displays on 2025-11-12).
-- NOTE: this file was never sourced by hyprland.conf and is likewise not
-- require()d by hyprland.lua. The DVI-I-1 / DVI-I-2 outputs do not exist on
-- this machine. Kept for reference; add `require("workspaces")` to
-- hyprland.lua to enable.

hl.workspace_rule({ workspace = "1", monitor = "eDP-1", default = true })
hl.workspace_rule({ workspace = "2", monitor = "DVI-I-1", default = true })
hl.workspace_rule({ workspace = "3", monitor = "DVI-I-2", default = true })
